server:
  port: 8080
spring:
  application:
    name: "cleanArchitecture"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8000"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "postgres"
    username: "postgres"
    password: "qwertyuiop12345678"
